__author__ = 'Tristan Newmann'

"""
MazeBuilder, Stroke Recovery Project, HMRI
Author: Tristan Newmann
Developed with 2.7

File: CustomWidgets.py

Module contains custom widgets for the MazeBuilder project
"""

/
# Imports
from UtilWidgets import ListHeap
from Tkinter import Menu
from Exceptions import DuplicateListHeapItemException, MaxItemLimitReachedException
import Debug


# Enumerations and Functions


# Classes


class PicConfigurator(ListHeap):
    """
    Defines a custom widget to be used for selecting texture pictures

    The PicConfigurator is a widget that extends the ListHeap widget. It has been specifically
    designed to allow the user to select textures to be used as pictures for the walls
    of nodes in the mazes

    The remainder if this is yet to be implemented, and will be completed during the backend phase

    Attributes:

    """
    def __init__(self, parent):
        """
        Construct and instance of PicConfigurator
        :param parent:      The parent tk item in which this widget will sit
        :return:            Instance of PicConfigurator
        """
        ListHeap.__init__(self, parent, 6)
        self.propagate(0)
        self.config(width=10, height=100)

    def _handle_db_click(self, event):
        """
        Handle mouse double click as a callback function

        Handles a mouse double click through the opening of an editing dialog
        for the picture item that was selected

        :param event:       The event generated by the window manager, automatically provided
        """
        Debug.printe(event, Debug.Level.INFO)
        # Open a room picture editing dialogue
        pass

    def _handle_r_click(self, event):
        """
        Handle mouse right click as a callback function

        Handle mouse right click by displaying a context menu for this widget,
        allow the addition and removal of window pics

        :param event:       The event generated by the window manager, automatically provided
        """
        Debug.printe(event, Debug.Level.INFO)
        # Create the menu to display
        p_menu = Menu(self._parent)
        p_menu.add_command(label="Add Picture", command=lambda: self._add_new_wall_pic())
        p_menu.add_command(label="Delete Picture", command=lambda: self._remove_wall_pic())
        p_menu.add_command(label="Delete All", command=lambda: self._remove_all())
        p_menu.post(event.x_root, event.y_root)

    def _add_new_wall_pic(self):
        """
        Adds a new wall picture to the node definition

        Launches a dialog, and validates and posts the entered information
        to the repository for the creation of a new wall picture for the
        node that is being edited
        """
        # Display the dialogue
        item_id = None
        item = None
        # Extract the return values
        try:
            self._add_new(item, item_id)
        except DuplicateListHeapItemException:
            Debug.printi("Unable to add duplicate picture", Debug.Level.ERROR)
            return
        except MaxItemLimitReachedException:
            Debug.printi("Maximum number of pictures for this room reached")
            return
        # TODO COMPLETE
        # Post the dialogue information to the *manager

    def _remove_wall_pic(self):
        """
        Remove the wall picture that is currently selected
        """
        # Retrieve the item that was selected
        key = None
        # Post a delete notice to the manager
        self.remove(key)

    def _remove_all(self):
        """
        Removes all of the wall pictures
        :return:
        """
        # Post a delete all notice to the manager
        self._remove_all()